// Checks the Dart port against outputs of the original Python app
// (test/fixtures/reference.json, generated by tool/gen_reference.py).

import 'dart:convert';
import 'dart:io';

import 'package:eqloader/core/autoeq.dart';
import 'package:eqloader/core/band.dart';
import 'package:eqloader/core/dsp.dart';
import 'package:eqloader/core/profile.dart';
import 'package:eqloader/core/walkplay.dart';
import 'package:flutter_test/flutter_test.dart';

Band bandFromJson(Map b) => Band(
  type: b['type'] as String,
  freq: (b['freq'] as num).toDouble(),
  gain: (b['gain'] as num).toDouble(),
  q: (b['q'] as num).toDouble(),
);

List<Point> curveFromJson(List pts) => [
  for (final p in pts) ((p[0] as num).toDouble(), (p[1] as num).toDouble()),
];

void main() {
  final ref = jsonDecode(
    File('test/fixtures/reference.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final bands = [for (final b in ref['bands'] as List) bandFromJson(b as Map)];

  test('filter packets are byte-identical', () {
    final packets = ref['packets'] as List;
    for (var i = 0; i < bands.length; i++) {
      expect(buildFilterPacket(i, bands[i], 2), packets[i], reason: '$i');
    }
  });

  test('packet parse inverts build', () {
    final b = Band(type: 'HSQ', freq: 8000, gain: -4.25, q: 0.9);
    final packet = buildFilterPacket(5, b, 1);
    final parsed = parseFilterPacket(packet);
    expect(parsed.index, 5);
    expect(parsed.band.type, 'HSQ');
    expect(parsed.band.freq, 8000);
    expect(parsed.band.gain, -4.25);
    expect(parsed.band.q, 0.9);
    expect(parsed.band.disabled, isFalse);
  });

  test('frequency response matches', () {
    final freqs = [
      for (final f in ref['response_freqs'] as List) (f as num).toDouble(),
    ];
    final responses = ref['response'] as Map;
    for (var i = 0; i < bands.length; i++) {
      final expected = responses['${bands[i].type}$i'] as List;
      final got = filtersResponseDb(freqs, [bands[i]]);
      for (var k = 0; k < freqs.length; k++) {
        expect(
          got[k],
          closeTo(expected[k] as num, 1e-9),
          reason: '$i @ ${freqs[k]}',
        );
      }
    }
    final all = filtersResponseDb(freqs, bands);
    final expectedAll = ref['response_all'] as List;
    for (var k = 0; k < freqs.length; k++) {
      expect(all[k], closeTo(expectedAll[k] as num, 1e-9));
    }
  });

  test('preamp register and Q/bandwidth conversions match', () {
    for (final row in ref['preamp_to_register'] as List) {
      expect(
        preampToRegister(
          (row[0] as num).toDouble(),
          (row[1] as num).toDouble(),
        ),
        row[2],
        reason: '$row',
      );
    }
    for (final row in ref['q_to_bw'] as List) {
      final q = (row[0] as num).toDouble();
      final bw = qToBw(q);
      expect(bw, closeTo(row[1] as num, 1e-12));
      expect(bwToQ(bw), closeTo(q, 1e-9));
    }
  });

  test('profiles load, filter and save like the Python app', () {
    final profiles = ref['profiles'] as Map;
    for (final MapEntry(:key, :value) in profiles.entries) {
      final p = value as Map;
      final profile = parseProfile(p['text'] as String);
      expect(profile.preamp, p['preamp'], reason: key as String);
      final active = activeFilters(profile.filters);
      final expected = [
        for (final b in p['active'] as List) bandFromJson(b as Map),
      ];
      expect(active.length, expected.length, reason: key);
      for (var i = 0; i < active.length; i++) {
        expect(
          active[i].toString(),
          expected[i].toString(),
          reason: '$key #$i',
        );
      }
      expect(
        formatProfile(profile.preamp, profile.filters),
        p['saved'],
        reason: key,
      );
    }
  });

  test('ISO 226 loudness offset matches', () {
    final m = curveFromJson(ref['autoeq']['measurement'] as List);
    expect(iso226FindOffset(m, 60), closeTo(ref['iso226_offset'] as num, 1e-9));
  });

  test('AutoEQ produces the same bands and preamp', () {
    final auto = ref['autoeq'] as Map;
    final m = curveFromJson(auto['measurement'] as List);
    final target = curveFromJson(auto['target'] as List);
    for (final c in auto['cases'] as List) {
      final result = autoeqCompute(
        m,
        c['flat'] as bool ? null : target,
        c['max_filters'] as int,
      );
      final expected = [
        for (final b in c['filters'] as List) bandFromJson(b as Map),
      ];
      expect(
        [for (final f in result.filters) f.toString()],
        [for (final f in expected) f.toString()],
        reason: 'max ${c['max_filters']} flat ${c['flat']}',
      );
      expect(result.preamp, c['preamp']);
    }
  }, timeout: const Timeout(Duration(minutes: 5)));
}
